version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_HOST=host.docker.internal
      - APP_PORT=${APP_PORT}
      - REDIRECT_HOST=host
      - REDIRECT_REQUEST_URI=request_uri
      - PROXY_HEADER_HOST=host
      - PROXY_HEADER_REMOTE_ADDR=remote_addr
      - PROXY_HEADER_X_FORWARDED_FOR=proxy_add_x_forwarded_for
      - PROXY_HEADER_PROTO=scheme
    command: /bin/bash -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
